import { formatYield } from '@/lib/utils/format';
import type { WaterfallResult } from '@/lib/tranche/types';

interface WaterfallBreakdownProps {
  result: WaterfallResult | null;
  activeScenario: string;
}

function yieldColor(amount: number): string {
  if (amount > 0.005) return 'text-emerald-400';
  if (amount < -0.005) return 'text-rose-400';
  return 'text-zinc-400';
}

function WaterfallRow({
  label,
  value,
  valueClass,
  sub,
  isTotal,
}: {
  label: string;
  value: string;
  valueClass?: string;
  sub?: string;
  isTotal?: boolean;
}) {
  return (
    <div className={`flex items-center justify-between py-2 ${isTotal ? 'border-t border-zinc-700 mt-1 pt-3' : ''}`}>
      <div>
        <span className={`text-sm ${isTotal ? 'font-semibold text-zinc-200' : 'text-zinc-400'}`}>{label}</span>
        {sub && <p className="text-xs text-zinc-600 mt-0.5">{sub}</p>}
      </div>
      <span className={`font-mono text-sm font-semibold ${valueClass ?? 'text-zinc-300'}`}>{value}</span>
    </div>
  );
}

export function WaterfallBreakdown({ result, activeScenario }: WaterfallBreakdownProps) {
  if (!result) {
    return (
      <div className="bg-zinc-900 rounded-xl border border-zinc-800 p-6">
        <p className="text-zinc-500 text-sm text-center py-4">
          Select a scenario above to view the waterfall breakdown.
        </p>
      </div>
    );
  }

  return (
    <div className="bg-zinc-900 rounded-xl border border-zinc-800 p-6">
      {/* Top waterfall rows */}
      <div className="divide-y divide-zinc-800/50">
        <WaterfallRow
          label="Gross Vault Yield"
          value={formatYield(result.grossYield)}
          valueClass={yieldColor(result.grossYield)}
          sub="Total yield generated by the base vault"
        />
        <WaterfallRow
          label="− Protocol Fee (0.5%)"
          value={result.protocolFeeAmount > 0 ? `−${formatYield(result.protocolFeeAmount).replace('+', '')}` : '$0.00'}
          valueClass="text-amber-400"
          sub="Management fee deducted from positive yield only"
        />
        <WaterfallRow
          label="= Distributable Yield"
          value={formatYield(result.distributableYield)}
          valueClass={yieldColor(result.distributableYield)}
          sub="Available for yield distribution"
          isTotal
        />
      </div>

      {/* Tranche split */}
      <div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">
        {/* Senior */}
        <div className="rounded-lg border border-indigo-700/40 bg-indigo-950/30 p-4">
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs font-semibold uppercase tracking-widest text-indigo-400">Protected</span>
            {result.seniorTargetMet ? (
              <span className="text-xs bg-emerald-900/50 text-emerald-400 border border-emerald-700/50 px-2 py-0.5 rounded-full">
                TARGET MET
              </span>
            ) : (
              <span className="text-xs bg-amber-900/50 text-amber-400 border border-amber-700/50 px-2 py-0.5 rounded-full">
                {result.distributableYield < 0 ? 'LOSS EVENT' : 'SHORT'}
              </span>
            )}
          </div>
          <p className={`text-xl font-bold font-mono ${yieldColor(result.seniorYield)}`}>
            {formatYield(result.seniorYield)}
          </p>
          <p className="text-xs text-indigo-300/60 mt-1">Priority — 10% annual target APY</p>
        </div>

        {/* Junior */}
        <div className="rounded-lg border border-amber-700/40 bg-amber-950/20 p-4">
          <div className="flex items-center justify-between mb-1">
            <span className="text-xs font-semibold uppercase tracking-widest text-amber-400">Buffer</span>
            {result.juniorExhausted ? (
              <span className="text-xs bg-rose-900/50 text-rose-400 border border-rose-700/50 px-2 py-0.5 rounded-full">
                EXHAUSTED
              </span>
            ) : result.distributableYield < 0 ? (
              <span className="text-xs bg-rose-900/50 text-rose-400 border border-rose-700/50 px-2 py-0.5 rounded-full">
                FIRST LOSS
              </span>
            ) : null}
          </div>
          <p className={`text-xl font-bold font-mono ${yieldColor(result.juniorYield)}`}>
            {formatYield(result.juniorYield)}
          </p>
          <p className="text-xs text-amber-300/60 mt-1">Residual — loss reserve</p>
        </div>
      </div>

      {/* Warning if senior absorbing losses */}
      {result.seniorAbsorbingLosses && (
        <div className="mt-3 rounded-lg border border-rose-500/40 bg-rose-950/30 px-3 py-2 text-xs text-rose-300">
          ⚠ Risk buffer exhausted — protected position is absorbing remaining losses.
        </div>
      )}
    </div>
  );
}
